# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(max_length=40)),
                ('add_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date added')),
                ('user_agent', models.CharField(default='', max_length=200)),
                ('ip_address', models.CharField(default='', max_length=15)),
                ('language', models.CharField(default='', max_length=5)),
                ('search_type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=5)),
                ('length', models.IntegerField()),
                ('part_of_speech', models.CharField(max_length=20, null=True)),
                ('definition', models.CharField(max_length=250, null=True)),
                ('name', models.BooleanField()),
                ('first1', models.CharField(max_length=1)),
                ('first2', models.CharField(max_length=2)),
                ('last1', models.CharField(max_length=1)),
                ('last2', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='found_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Word'),
        ),
    ]
